export { isCompactMode, isEmbedMode, applyEmbedDocumentAttrs } from '@/embed/mode'
export { EMBED_MESSAGE_SOURCE, isEmbedSyncMessage } from '@/embed/protocol'
export type { EmbedSyncMessage } from '@/embed/protocol'
export { applyJugruHostSync } from '@/embed/host/jugru'
export { useWidgetBridge } from '@/embed/useWidgetBridge'
