export { default as RatingPanel } from '@/components/RatingPanel.vue'
export { formatResultsText, useTalkRating } from '@/composables/useTalkRating'
export { criteria } from '@/config/ratingCriteria'
export { syncToJugru } from '@/jugru/sync'
export type { Criterion, CriterionId, CriterionScore } from '@/types/rating'
